# Instructions to run this makefile
# Simply run make in the terminal and this file will take care of 
# Producing required results

lab2: lab2.o
	g++ lab2.o -o lab2

lab2.o: lab2.cpp
	g++ -c lab2.cpp

clean: 
	rm *.o math