lab3: main.o ReadWrite.o StudentGrade.o GradeRate.o
	g++ main.o ReadWrite.o StudentGrade.o GradeRate.o -o lab3

main.o: ./src/main.cpp
	g++ -c ./src/main.cpp

ReadWrite.o: ./src/ReadWrite.cpp
	g++ -c ./src/ReadWrite.cpp

StudentGrade.o: ./src/StudentGrade.cpp
	g++ -c ./src/StudentGrade.cpp

GradeRate.o: ./src/GradeRate.cpp
	g++ -c ./src/GradeRate.cpp